name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-${{ github.event.pull_request.number || '' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
          
      - name: Install
        run: npm ci

      - name: Env validate
        run: npm run env:validate
      
      - name: Lint
        run: npm run lint
        
      - name: (Placeholder) Tests (non-blocking)
        run: |
          if npm run test --if-present; then
            echo "Test script ran (or no test script defined)."
          else
            echo "::warning::Test script failed (ignored for now)."
          fi
        continue-on-error: true
        
      - name: Build
        run: npm run build
        
      - name: Upload backend artifact
        if: success() && hashFiles('backend/dist/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist
      - name: Upload frontend artifact
        if: success() && hashFiles('frontend/dist/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
